workspace = { members = [ "hello_wprld","hellow_world", "rust-is-easy"] }
[package]
name = "data-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
